version: '1.0'

services:
  web:
    build: .
    container_name: fastapi
    command: uvicorn main:app --port=8001 --host=0.0.0.0 --reload
    env_file:
      - ./backend/.env.production
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app