name: ttds-scraper
channels:
  - defaults
  - conda-forge
dependencies:
  - abseil-cpp=20230802.0
  - aiohttp=3.9.3
  - aiosignal=1.2.0
  - anyio=3.7.1
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - arrow-cpp=14.0.2
  - asttokens=2.2.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - comm=0.1.4
  - contourpy=1.0.5
  - cryptography=41.0.7
  - cycler=0.11.0
  - debugpy=1.6.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fastavro=1.9.1
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gflags=2.2.2
  - glog=0.5.0
  - google-api-core=1.34.0
  - google-api-core-grpc=1.34.0
  - google-cloud-bigquery=2.1.0
  - google-cloud-bigquery-core=2.1.0
  - google-cloud-bigquery-storage=2.24.0
  - google-cloud-bigquery-storage-core=2.24.0
  - google-cloud-core=1.7.1
  - google-crc32c=1.5.0
  - google-resumable-media=1.3.1
  - googleapis-common-protos=1.56.4
  - grpc-cpp=1.48.2
  - grpcio-status=1.41.1
  - gtest=1.14.0
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.1
  - ipython=8.14.0
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonpointer=2.0
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.5
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupytext=1.16.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libjpeg-turbo=2.1.5.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.2
  - mistune=3.0.1
  - multidict=6.0.4
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=7.0.2
  - notebook-shim=0.2.3
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openfst=1.8.3
  - openjpeg=2.5.0
  - openssl=3.2.1
  - orc=1.7.4
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.0
  - send2trash=1.8.2
  - setuptools=68.1.2
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - uri-template=1.3.0
  - urllib3=2.0.4
  - utf8proc=2.6.1
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.2
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - aioredis==1.3.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - asyncio==3.4.3
      - cachetools==5.3.1
      - click==8.1.7
      - ffmpy==0.3.1
      - flatbuffers==23.5.26
      - gast==0.5.4
      - gevent==23.9.1
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - google-cloud-secret-manager==2.18.1
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpc-google-iam-v1==0.13.0
      - grpcio==1.59.0
      - h11==0.14.0
      - h5py==3.9.0
      - hiredis==2.3.2
      - html5lib==1.1
      - ipywidgets==8.1.1
      - joblib==1.3.2
      - jupyterlab-widgets==3.0.9
      - keras==2.14.0
      - libclang==16.0.6
      - lxml==5.1.0
      - markdown==3.5
      - ml-dtypes==0.2.0
      - nltk==3.8.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - outcome==1.3.0.post0
      - proto-plus==1.23.0
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - redis==5.0.1
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.11.3
      - selenium==4.16.0
      - sortedcontainers==2.4.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.14.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - trio==0.24.0
      - trio-websocket==0.11.1
      - werkzeug==3.0.0
      - widgetsnbextension==4.0.9
      - wrapt==1.14.1
      - wsproto==1.2.0
      - xgboost==2.0.2
      - xmltodict==0.13.0
      - zope-event==5.0
      - zope-interface==6.1
