name: Deploy fastapi
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2
    
    - name: install gcloud cli
      uses: google-github-actions/setup-glcoud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: build and push docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        docker build -t europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest .
        docker push europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest

      