name: Deploy fastapi
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    permissions:
        contents: 'read'
        id-token: 'write'
        
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: authenticate gcloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
        export_default_credentials: true


    - name: build and push docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        docker build -t europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest .
        docker push europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest

      