name: Deploy fastapi
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    permissions:
        contents: 'read'
        id-token: 'write'
        
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - name: authenticate gcloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: build and push docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west2-docker.pkg.dev
        docker build -t europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest .
        docker push europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest
    
    - name: delete all deployed services
      run: |
        for service in $(gcloud run services list --platform managed --region europe-west1 --format="value(SERVICE)"); do
          gcloud run services delete $service --platform managed --region europe-west1 --quiet
        done

    - name: deploy to cloud run
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        gcloud run deploy fastapi \
          --image=europe-west2-docker.pkg.dev/grounded-hull-413601/ttds/fastapi:latest \
          --platform=managed \
          --region=europe-west1 \
          --update-env-vars TESTING=789 \
          --allow-unauthenticated